import { motion } from 'framer-motion';
import { ArrowUpRight, Github } from 'lucide-react';
const projects = [
  { n: '01', title: 'Semente Digital', desc: 'Plataforma de divulgação sobre desenvolvimento sustentável aplicado à engenharia.', tags: ['React', 'JavaScript', 'Vercel'], live: 'https://sementedigital.vercel.app/', code: 'https://github.com/gabrielcattuzo/semente.digital', color: 'green' },
  { n: '02', title: 'Batalha Naval', desc: 'Jogo completo desenvolvido em Assembly x86, explorando registradores, memória e interrupções.', tags: ['Assembly x86', 'DOSBox'], code: 'https://github.com/gabrielcattuzo/batalha-naval-assembly', color: 'blue' },
  { n: '03', title: 'Projeto DevWeb', desc: 'Aplicação com autenticação Firebase e integração a APIs de comunicação.', tags: ['Firebase', 'Node.js', 'APIs'], live: 'https://projeto-devweb.vercel.app/', code: 'https://github.com/gabrielcattuzo/PROJETO-DEVWEB', color: 'orange' },
  { n: '04', title: 'Voe Sempre', desc: 'Sistema em C para cadastro e gerenciamento de voos de uma companhia aérea.', tags: ['C', 'Estruturas de dados'], code: 'https://github.com/gabrielcattuzo/voe-sempre', color: 'violet' },
  { n: '05', title: 'Cofre digital', desc: 'Simulação de cofre e operações com barramentos e deslocamentos em C.', tags: ['C', 'Baixo nível'], code: 'https://github.com/gabrielcattuzo/cofre', color: 'red' },
  { n: '06', title: 'Tesla Turbine', desc: 'Simulador web para explorar parâmetros e valores de uma turbina de Tesla.', tags: ['React', 'JavaScript'], code: 'https://github.com/gabrielcattuzo/teslaturbine', color: 'cyan' },
];
const Projects = () => <section id="projetos" className="section section-projects"><div className="site-shell"><div className="section-heading projects-heading"><div><p className="section-index">03 / PROJETOS</p><h2>Trabalho selecionado.</h2></div><a href="https://github.com/gabrielcattuzo?tab=repositories" target="_blank" rel="noreferrer">Ver todos no GitHub <ArrowUpRight size={17} /></a></div><div className="projects-grid">{projects.map((p, i) => <motion.article className={`project-card ${p.color}`} key={p.title} initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .06 }}><div className="project-visual"><span>{p.n}</span><div className="visual-code">{p.title.split(' ').map((word, idx) => <i key={word}>{idx === 0 ? '>' : '·'} {word}</i>)}</div></div><div className="project-content"><div><h3>{p.title}</h3><p>{p.desc}</p></div><div className="project-bottom"><div>{p.tags.map(t => <span key={t}>{t}</span>)}</div><aside>{p.live && <a href={p.live} target="_blank" rel="noreferrer" aria-label="Abrir projeto"><ArrowUpRight /></a>}<a href={p.code} target="_blank" rel="noreferrer" aria-label="Abrir código"><Github /></a></aside></div></div></motion.article>)}</div></div></section>;
export default Projects;
